export var DEVELOPER_MODE = 1

export var VERSION = "0.2.0"
export var VERSION_PREFIX = "Blog Version: V"

var VERSION_SUFFIX = ""
var VERSION_DEV_SUFFIX = "_dev"

if(DEVELOPER_MODE == 1) {
  VERSION_SUFFIX = VERSION_SUFFIX + VERSION_DEV_SUFFIX 
}

export { VERSION_SUFFIX }
