import { throwError } from '/Blog/SP/util/error.js';

// This are functions generated by ChatGPT
// Might not work, Might work, we will see.
// Modified if necessary.

// Function to read a file from the website
export function readFile(filePath) {
    try {
        // Fetch the file from the given file path
        const response = await fetch(filePath);

        // Check if the response is successful
        if (!response.ok) {
           return error('Network response was not ok ' + response.statusText);
        }

        // Get the text content of the file
        const text = await response.text();

        // Process the file content (for example, log it to the console)
        console.log(text);

        // You can also return the file content if needed
        return text;
        
    } catch (err) {
        return error('There was a problem with the fetch operation:' + err);
    }
}

function error(msg) {
    throwError(msg);
    return msg;
}
