import { throwError } from '/Blog/SP/util/error.js';

// This are functions generated by ChatGPT
// Might not work, Might work, we will see.
// Modified if necessary.

// Function to read a file from the website
export function readFile(filePath) {
    try {
        // Fetch the file from the given file path
        const response = await fetch(filePath);

        // Check if the response is successful
        if (!response.ok) {
            
           var err_msg = 'Network response was not ok ' + response.statusText;
            
            throwError(err_msg);
            return err_msg;
            
        }

        // Get the text content of the file
        const text = await response.text();

        // Process the file content (for example, log it to the console)
        console.log(text);

        // You can also return the file content if needed
        return text;
        
    } catch (error) {
        
        var err_msg = 'There was a problem with the fetch operation:' + error;

        throwError(err_msg);
        return err_msg;
        
    }
}
